/**
 * 網站貢獻名單（TAIGIE-236）
 *
 * 資料來源：PM 提供的 Google 試算表「網站貢獻名單」分頁（B 欄姓名、C／D 欄貢獻項目），
 * 對應 2026-09-09 PM 移除重複填寫後的版本。
 * PM 於 2026-09-09 確認名單近半年內不太會更動，先以前端寫死處理；
 * 若之後要讓管理員自行增修（PM 預計今年底前確認是否需要），再改為後端 API ＋ 後台管理頁。
 *
 * 維護規則：
 * - 陣列順序即為畫面上的類別順序（PM 指定，勿自行調整）。
 * - 同一人參與多項工作時會同時出現在多個類別，這是預期行為；但**同一類別內不重複列名**。
 * - 名單依「姓名筆畫少到多」排序：逐字比較筆畫數，第一字相同再比下一字。
 *   筆畫數採教育部 CNS11643 全字庫（`CNS_stroke.txt`）的官方數值 —— 注意多數程式庫（含 Unihan
 *   kTotalStrokes）用的是中國大陸算法，會把「陳」算成 10 畫，排序結果與台灣習慣不同。
 *   非漢字姓名排在該類別最後。新增人員時請一併維持這個順序。
 * - 類別若有 `subgroups`，代表該類別底下再分小段，每段一個標題；沒有的就用 `people`。
 *   「內容提供與授權」原本是在每個姓名後各自標註貢獻內容，但 37/38 人的內容相同、畫面過於冗長，
 *   PM 於 2026-09-09 同意改為分小段呈現。子分組依人數由多到少排列。
 */
const contributorsData = [
  {
    category: '專案主持',
    people: [
      { name: '張婉鈴' },
      { name: '陳麗君' },
      { name: '楊佳翰' },
      { name: '盧文祥' },
    ],
  },
  {
    category: '專案執行與行政支援',
    people: [
      { name: '丁竟烽' },
      { name: '方宣又' },
      { name: '王景霈' },
      { name: '吳芛君' },
      { name: '呂竺芸' },
      { name: '吳佳雯' },
      { name: '沈宛瑩' },
      { name: '李宗翰' },
      { name: '吳亭誼' },
      { name: '吳俊穎' },
      { name: '吳珮安' },
      { name: '呂紹瑜' },
      { name: '李熙堃' },
      { name: '林守威' },
      { name: '林怡君' },
      { name: '邱家浩' },
      { name: '林雅惠' },
      { name: '胡旻鈞' },
      { name: '洪柔安' },
      { name: '徐向廷' },
      { name: '陳思云' },
      { name: '陳品璇' },
      { name: '梁雅婷' },
      { name: '游子萱' },
      { name: '傅孟楷' },
      { name: '黃詩晴' },
      { name: '葉威呈' },
      { name: '劉金丞' },
      { name: '蕭郁霖' },
      { name: '藍君偉' },
      { name: '鐘鳳喜' },
      { name: 'Sangas Losing' },
    ],
  },
  {
    category: '網站設計與開發',
    people: [
      { name: '吳亭誼' },
      { name: '吳俊穎' },
      { name: '林旻萱' },
      { name: '徐向廷' },
      { name: '陳念誠' },
      { name: '陳彥安' },
      { name: '梁雅婷' },
      { name: '蕭郁霖' },
      { name: '謝宗佑' },
      { name: '藍君偉' },
    ],
  },
  {
    category: '插畫與視覺設計',
    people: [
      { name: '周亮羽' },
      { name: '蔡易霖' },
    ],
  },
  {
    category: '內容整理與編輯',
    people: [
      { name: '王維震' },
      { name: '吳亞芝' },
      { name: '余宥潔' },
      { name: '林子喻' },
      { name: '林芷妤' },
      { name: '林俊義' },
      { name: '洪憶心' },
      { name: '施懿庭' },
      { name: '孫子芸' },
      { name: '高家和' },
      { name: '孫翊倫' },
      { name: '張之瑜' },
      { name: '陳佩希' },
      { name: '陳虹亦' },
      { name: '張苡薰' },
      { name: '陳雅妮' },
      { name: '莊喻涵' },
      { name: '張琮勛' },
      { name: '張壹喬' },
      { name: '許睿珊' },
      { name: '黃友弟' },
      { name: '馮承詣' },
      { name: '劉佳樂' },
      { name: '劉亭楟' },
      { name: '潘淑球' },
      { name: '穆伊莉' },
      { name: '藍君偉' },
      { name: 'Sangas Losing' },
    ],
  },
  {
    category: '俗諺語內容建置',
    people: [
      { name: '尤千萍' },
      { name: '王昱臻' },
      { name: '王彩薰' },
      { name: '王雅玲' },
      { name: '王琬淳' },
      { name: '王惠瑩' },
      { name: '白祐瑄' },
      { name: '吳秀蘭' },
      { name: '李宛青' },
      { name: '李宜芝' },
      { name: '吳宗勇' },
      { name: '李明哲' },
      { name: '李芷葳' },
      { name: '余明憲' },
      { name: '余佳燕' },
      { name: '吳政諺' },
      { name: '吳淑媛' },
      { name: '李菁怡' },
      { name: '呂聯輝' },
      { name: '吳麗華' },
      { name: '林宗賢' },
      { name: '邱偉欣' },
      { name: '周惠嫺' },
      { name: '林睿展' },
      { name: '柯育佳' },
      { name: '洪國勛' },
      { name: '洪慧君' },
      { name: '翁凱毅' },
      { name: '翁慧慈' },
      { name: '陳正恩' },
      { name: '張巧慧' },
      { name: '陳金月' },
      { name: '陳明君' },
      { name: '陳宗儀' },
      { name: '陳怡靜' },
      { name: '陳盈如' },
      { name: '郭奕涵' },
      { name: '陳宥瑋' },
      { name: '郭春輝' },
      { name: '陳雅文' },
      { name: '陳舜怡' },
      { name: '陳凱萍' },
      { name: '陳雅蕙' },
      { name: '陳富樺' },
      { name: '許暉東' },
      { name: '陳語涵' },
      { name: '陳銘鴻' },
      { name: '許靜雪' },
      { name: '黃子庭' },
      { name: '黃昭華' },
      { name: '黃昭勳' },
      { name: '黃鈺雯' },
      { name: '黃話雯' },
      { name: '黃詩維' },
      { name: '黃慧娟' },
      { name: '黃馨儀' },
      { name: '葉佩瑜' },
      { name: '楊曉君' },
      { name: '廖恩羽' },
      { name: '劉文正' },
      { name: '鄭元鈞' },
      { name: '蔡孟欣' },
      { name: '蔡政君' },
      { name: '劉家吟' },
      { name: '劉軒豪' },
      { name: '蔡菽娟' },
      { name: '蔡詩盈' },
      { name: '劉曉玫' },
      { name: '賴仁義' },
      { name: '賴素鈴' },
      { name: '謝青樺' },
      { name: '顏雨詩' },
    ],
  },
  {
    category: '台語出名人內容建置',
    people: [
      { name: '陳宥瑋' },
      { name: '陳語涵' },
    ],
  },
  {
    category: '工作坊執行支援',
    people: [
      { name: '丁久芳' },
      { name: '朱翔歆' },
      { name: '吳韋蓁' },
      { name: '林千資' },
      { name: '林旻萱' },
      { name: '林曉君' },
      { name: '徐芊右' },
      { name: '唐偉婷' },
      { name: '馬薏萍' },
      { name: '張品儀' },
      { name: '許庭瑜' },
      { name: '謝佳蓉' },
    ],
  },
  {
    category: '教師工作坊參與',
    people: [
      { name: '朱志煒' },
      { name: '李宜家' },
      { name: '李虹虹' },
      { name: '吳春禧' },
      { name: '林良吉' },
      { name: '林彥君' },
      { name: '林婕媮' },
      { name: '姚雅芳' },
      { name: '洪憶心' },
      { name: '張沛瑜' },
      { name: '張宏嘉' },
      { name: '張芳伶' },
      { name: '張芷姍' },
      { name: '許芸萱' },
      { name: '許惠如' },
      { name: '許貴菊' },
      { name: '陳鈺琪' },
      { name: '許靜雪' },
      { name: '陳寶玲' },
      { name: '黃昭勳' },
      { name: '蔡天享' },
      { name: '潘志鴻' },
      { name: '鄭素卿' },
      { name: '盧叔欣' },
      { name: '賴明澄' },
      { name: '顏宏鉎' },
      { name: '顏雨詩' },
      { name: '蘇美玉' },
    ],
  },
  {
    category: '學生工作坊參與',
    people: [
      { name: '才宛妤' },
      { name: '王玟凌' },
      { name: '王品欣' },
      { name: '王禹晴' },
      { name: '方偉澤' },
      { name: '全禹瑄' },
      { name: '吳羽峻' },
      { name: '吳佑庭' },
      { name: '吳昀妮' },
      { name: '李佾洋' },
      { name: '何采穎' },
      { name: '汪俊廷' },
      { name: '李翊愷' },
      { name: '邢殿君' },
      { name: '吳潔心' },
      { name: '李諺' },
      { name: '卓子翔' },
      { name: '林玥妤' },
      { name: '林芝嘉' },
      { name: '林品陞' },
      { name: '林耘竹' },
      { name: '林婉萱' },
      { name: '侯奕亘' },
      { name: '洪亮葳' },
      { name: '洪偉翔' },
      { name: '洪璟軒' },
      { name: '倪恩芝' },
      { name: '翁晉傑' },
      { name: '孫翊倫' },
      { name: '高嘉萍' },
      { name: '高韻瑄' },
      { name: '許天青' },
      { name: '陳文賓' },
      { name: '張文寶' },
      { name: '陳沛淳' },
      { name: '陳邑睿' },
      { name: '陳昀希' },
      { name: '陳秉宏' },
      { name: '郭旻昕' },
      { name: '郭芮瑄' },
      { name: '許芮瑜' },
      { name: '許芮綺' },
      { name: '郭采寧' },
      { name: '陳泓銓' },
      { name: '陳柔安' },
      { name: '陳姿伶' },
      { name: '陳奕慈' },
      { name: '陳宥蓁' },
      { name: '陳宥臻' },
      { name: '陳柏諺' },
      { name: '張苡薰' },
      { name: '張耘榛' },
      { name: '梁祐禎' },
      { name: '莊琇涵' },
      { name: '陳喬芬' },
      { name: '陳湞庭' },
      { name: '許詠晴' },
      { name: '張程翔' },
      { name: '張詠晴' },
      { name: '陳歆' },
      { name: '郭憫宥' },
      { name: '陳穎柔' },
      { name: '彭于芩' },
      { name: '黃妤萱' },
      { name: '黃欣惠' },
      { name: '黃冠瑜' },
      { name: '黃啓軒' },
      { name: '黃詩芸' },
      { name: '黃靖婷' },
      { name: '黃煜凱' },
      { name: '黃楀晴' },
      { name: '楊尹庠' },
      { name: '楊云喬' },
      { name: '葉怡辰' },
      { name: '楊淵丞' },
      { name: '楊閔媗' },
      { name: '楊喻婷' },
      { name: '詹詩婷' },
      { name: '蔡沁妮' },
      { name: '鄭欣瑜' },
      { name: '蔡品柔' },
      { name: '蔡釩瑜' },
      { name: '蔡媃羽' },
      { name: '歐陽靚' },
      { name: '潘靖姍' },
      { name: '蔡璨容' },
      { name: '歐懷謙' },
      { name: '賴冠宏' },
      { name: '戴可欣' },
      { name: '戴麒霖' },
      { name: '魏柏睿' },
      { name: '羅婕昌' },
      { name: '蘇芳嫻' },
      { name: '蘇彥如' },
      { name: '蘇槿萱' },
    ],
  },
  {
    category: '內容提供與授權',
    subgroups: [
      {
        label: '台語出名人作品提供與授權',
        people: [
          { name: '王育德' },
          { name: '巴克禮' },
          { name: '王貞文' },
          { name: '王昭華' },
          { name: '王羅蜜多' },
          { name: '方耀乾' },
          { name: '向陽' },
          { name: '杜信龍' },
          { name: '李勤岸' },
          { name: '宋澤萊' },
          { name: '林央敏' },
          { name: '林宗源' },
          { name: '林茂生' },
          { name: '林美麗' },
          { name: '林裕凱' },
          { name: '胡民祥' },
          { name: '柯柏榮' },
          { name: '柯旗化' },
          { name: '陳正雄' },
          { name: '陳明仁' },
          { name: '陳金順' },
          { name: '郭秋生' },
          { name: '陳清忠' },
          { name: '陳雷' },
          { name: '黃石輝' },
          { name: '黃勁連' },
          { name: '路寒袖' },
          { name: '鄭兒玉' },
          { name: '劉承賢' },
          { name: '蔡培火' },
          { name: '賴仁聲' },
          { name: '蕭平治' },
          { name: '賴和' },
          { name: '戴仁壽' },
          { name: '藍春瑞' },
          { name: '藍淑貞' },
          { name: '顧德莎' },
        ],
      },
      {
        label: '台語做伙耍網站主持人',
        people: [
          { name: '莊雅雯' },
        ],
      },
    ],
  },
  {
    category: '合作廠商',
    people: [
      { name: '吳泓瑞' },
      { name: '林彥明' },
    ],
  },
];

export default contributorsData;
